public enum EComponents
{
    Main_Camera,
    Warrior,
    Enemy_HM,
    Enemy_CM,
    Enemy_Spawner,
    Enemy_Spawner_Point,
    Environment,
    SceneLoader,
    UIRoot,
    Projectile_Blue,
    Projectile_Red,
    Projectile_Green,
    Projectile_Purple,
    MusicAudioMixer,
    EffectsAudioMixer,
    AudioListener
}
